# Generated by Django 5.0.7 on 2026-03-19 17:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_code', models.CharField(blank=True, default='', max_length=80)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='staff.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='staff.designation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='shared.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffIDProof',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('aadhar', 'Aadhar'), ('pan', 'Pan'), ('passport', 'Passport'), ('other', 'Other')], default='other', max_length=20)),
                ('number', models.CharField(blank=True, default='', max_length=100)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('document_metadata', models.JSONField(blank=True, default=dict)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proofs', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAvailabilityOverride',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_overrides', to='shared.hospital')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_availability', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_overrides', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffShiftAssignment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='shared.hospital')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='staff.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='staff.staffprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['hospital', 'name'], name='staff_depar_hospita_4ac08f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['hospital', 'name'], name='staff_desig_hospita_97a529_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('hospital', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('hospital', 'name')},
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['hospital', 'employee_code'], name='staff_staff_hospita_370df9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffidproof',
            index=models.Index(fields=['staff', 'proof_type'], name='staff_staff_staff_i_e19ac4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffavailabilityoverride',
            unique_together={('hospital', 'staff', 'date')},
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['staff', 'phone'], name='staff_emerg_staff_i_6d1138_idx'),
        ),
        migrations.AddIndex(
            model_name='staffshiftassignment',
            index=models.Index(fields=['hospital', 'date'], name='staff_staff_hospita_066d82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffshiftassignment',
            unique_together={('hospital', 'staff', 'date')},
        ),
    ]
