# Generated by Django 5.0.7 on 2026-03-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
