# Generated by Django 5.0.7 on 2026-03-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('staff', '0002_department_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'code'), ('hospital', 'name')},
        ),
    ]
