# Generated by Django 5.0.7 on 2026-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('staff', '0003_department_unique_name_per_hospital'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
