# Generated by Django 5.0.7 on 2026-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshiftassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
