# Generated by Django 5.0.7 on 2026-04-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='validation_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_group_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='procedure',
            field=models.TextField(blank=True, default=''),
        ),
    ]
