# Generated by Django 5.0.7 on 2026-03-19 17:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0001_initial'),
        ('patients', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDAdmission',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('ward_name', models.CharField(blank=True, default='', max_length=200)),
                ('room_name', models.CharField(blank=True, default='', max_length=200)),
                ('bed_code', models.CharField(blank=True, default='', max_length=100)),
                ('admission_diagnosis', models.TextField(blank=True, default='')),
                ('admission_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('transferred', 'Transferred'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled')], db_index=True, default='admitted', max_length=20)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True, default='')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions_as_nurse', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='shared.hospital')),
                ('opd_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_conversions', to='opd.opdvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='IPDAdmissionStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ipd.ipdadmission')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPDTransferHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_ward_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_ward_name', models.CharField(blank=True, default='', max_length=200)),
                ('from_room_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_room_name', models.CharField(blank=True, default='', max_length=200)),
                ('from_bed_code', models.CharField(blank=True, default='', max_length=100)),
                ('to_bed_code', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='ipd.ipdadmission')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='ipdadmission',
            index=models.Index(fields=['hospital', 'admission_date'], name='ipd_ipdadmi_hospita_a248b4_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdadmission',
            index=models.Index(fields=['hospital', 'assigned_doctor', 'admission_date'], name='ipd_ipdadmi_hospita_5c435e_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdadmission',
            index=models.Index(fields=['patient', 'admission_date'], name='ipd_ipdadmi_patient_e65c44_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdadmissionstatushistory',
            index=models.Index(fields=['admission', 'to_status'], name='ipd_ipdadmi_admissi_2e6a6d_idx'),
        ),
    ]
