# Generated by Django 5.0.7 on 2026-04-01 02:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipd', '0001_initial'),
        ('shared', '0001_initial'),
        ('staff', '0005_staffshiftassignment_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='shared.hospital')),
                ('ipd_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='ipd.ipdadmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('instructions', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('medication', 'Medication'), ('nursing', 'Nursing care'), ('physiotherapy', 'Physiotherapy'), ('investigation', 'Investigation'), ('diet', 'Diet'), ('other', 'Other')], db_index=True, default='medication', max_length=30)),
                ('day_offset', models.PositiveSmallIntegerField(default=0)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plan_items', to='staff.department')),
                ('assigned_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plan_items', to='staff.designation')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plan_items', to='staff.staffprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treatment.treatmentplanitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treatment.treatmentplan')),
            ],
            options={
                'ordering': ['day_offset', 'time_of_day', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentTask',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('stat', 'Stat (Immediate)')], db_index=True, default='normal', max_length=10)),
                ('notes_from_doctor', models.TextField(blank=True, default='')),
                ('notes_from_staff', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_tasks', to='staff.staffprofile')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_treatment_tasks', to=settings.AUTH_USER_MODEL)),
                ('ipd_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_tasks', to='ipd.ipdadmission')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='treatment.treatmentplanitem')),
            ],
            options={
                'ordering': ['date', 'time_of_day', 'priority'],
            },
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['hospital', 'status'], name='treatment_t_hospita_06b24e_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['ipd_admission', 'status'], name='treatment_t_ipd_adm_547d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['plan', 'day_offset'], name='treatment_t_plan_id_c65b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['plan', 'category'], name='treatment_t_plan_id_f77390_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmenttask',
            index=models.Index(fields=['ipd_admission', 'date', 'status'], name='treatment_t_ipd_adm_b77738_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmenttask',
            index=models.Index(fields=['assigned_staff', 'date', 'status'], name='treatment_t_assigne_a79041_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmenttask',
            constraint=models.UniqueConstraint(fields=('plan_item', 'date'), name='treatment_unique_task_per_item_per_date'),
        ),
    ]
