# Generated by Django 5.0.7 on 2026-04-14 17:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffshiftassignment_end_date'),
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlanStaffAssignment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_label', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tp_staff_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='treatment.treatmentplan')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan_assignments', to='staff.staffprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['plan', 'staff'], name='treatment_t_plan_id_37a2fe_idx')],
                'unique_together': {('plan', 'staff')},
            },
        ),
    ]
