# Generated by Django 5.0.7 on 2026-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_patienttimeline'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patienttimeline',
            new_name='treatment_p_hospita_df1293_idx',
            old_name='treatment_p_hospita_abf9ec_idx',
        ),
        migrations.RenameIndex(
            model_name='patienttimeline',
            new_name='treatment_p_ipd_adm_a2beef_idx',
            old_name='treatment_p_ipd_ad_9e83f0_idx',
        ),
        migrations.RenameIndex(
            model_name='patienttimeline',
            new_name='treatment_p_event_t_341ee2_idx',
            old_name='treatment_p_event_t_f9a1d9_idx',
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
    ]
