# Generated by Django 5.0.7 on 2026-03-19 17:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipd', '0001_initial'),
        ('opd', '0001_initial'),
        ('patients', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_no', models.CharField(max_length=60)),
                ('encounter_type', models.CharField(choices=[('opd', 'Opd'), ('ipd', 'Ipd'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('package', 'Package')], default='opd', max_length=20)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cancelled_reason', models.CharField(blank=True, default='', max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='shared.hospital')),
                ('ipd_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='ipd.ipdadmission')),
                ('opd_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='opd.opdvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DailyClosingSummary',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closing_date', models.DateField()),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closings', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.billinginvoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_sequences', to='shared.hospital')),
            ],
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['hospital', 'invoice_date'], name='billing_bil_hospita_09ad58_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['hospital', 'status'], name='billing_bil_hospita_0d47b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billinginvoice',
            unique_together={('hospital', 'invoice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyclosingsummary',
            unique_together={('hospital', 'closing_date')},
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'description'], name='billing_inv_invoice_871e67_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenumbersequence',
            index=models.Index(fields=['hospital', 'year'], name='billing_inv_hospita_5f8f41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicenumbersequence',
            unique_together={('hospital', 'year')},
        ),
    ]
