# Generated by Django 5.0.7 on 2026-03-19 17:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('queue_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('visit_reason', models.TextField(blank=True, default='')),
                ('symptoms', models.TextField(blank=True, default='')),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('consultation_notes', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('test_recommendations', models.TextField(blank=True, default='')),
                ('revisit_advice', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('doctor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits', to='shared.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OPDVisitStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_status_changes', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='opd.opdvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['hospital', 'visit_date'], name='opd_opdvisi_hospita_26beaf_idx'),
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['hospital', 'doctor_user', 'visit_date'], name='opd_opdvisi_hospita_e0f2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['patient', 'visit_date'], name='opd_opdvisi_patient_2bbbdc_idx'),
        ),
    ]
