# Generated by Django 5.0.7 on 2026-04-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='follow_up_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
