# Generated by Django 5.0.7 on 2026-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_add_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='follow_up_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
