# Generated by Django 5.0.7 on 2026-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_add_follow_up_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
