# Generated by Django 5.0.7 on 2026-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_opdvisit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
