# Generated by Django 5.0.7 on 2026-04-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_opdvisit_payment_mode'),
        ('patients', '0002_make_last_name_optional'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['hospital', 'created_by', 'visit_date'], name='opd_opdvisi_hospita_f07dd8_idx'),
        ),
    ]
