# Generated by Django 5.0.7 on 2026-03-19 17:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('token_number', models.PositiveIntegerField(db_index=True)),
                ('queue_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='appointments.appointment')),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='called_tokens', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='doctors.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='shared.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TokenStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tokens.token')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTokenCounter',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_counters', to='doctors.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_counters', to='shared.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'date', 'doctor'], name='tokens_dail_hospita_7cfb47_idx')],
                'unique_together': {('hospital', 'doctor', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['hospital', 'doctor', 'date', 'status'], name='tokens_toke_hospita_40798b_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['hospital', 'patient', 'date'], name='tokens_toke_hospita_660fd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('hospital', 'doctor', 'date', 'token_number')},
        ),
        migrations.AddIndex(
            model_name='tokenstatushistory',
            index=models.Index(fields=['token', 'to_status'], name='tokens_toke_token_i_488d16_idx'),
        ),
    ]
