# Generated by Django 5.0.7 on 2026-03-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0002_rolefieldpermission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rolefieldpermission',
            new_name='roles_permi_role_id_e90b38_idx',
            old_name='roles_permi_role_id_a66d0f_idx',
        ),
    ]
