# Generated by Django 5.0.7 on 2026-03-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0004_designationmodulepermission_designationpermissionsetup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Users permission', 'verbose_name_plural': 'Users permissions'},
        ),
    ]
