# Generated by Django 5.0.7 on 2026-03-30 17:35

from django.db import migrations, models


def forwards_enable_actions_for_active_links(apps, schema_editor):
    Link = apps.get_model("roles_permissions", "DesignationModulePermission")
    Link.objects.filter(is_active=True).update(
        can_add=True,
        can_edit=True,
        can_delete=True,
        can_view=True,
        can_print=True,
        can_download=True,
    )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0006_designation_permission_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationmodulepermission',
            name='can_add',
            field=models.BooleanField(default=False, verbose_name='Add'),
        ),
        migrations.AddField(
            model_name='designationmodulepermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='designationmodulepermission',
            name='can_download',
            field=models.BooleanField(default=False, verbose_name='Download'),
        ),
        migrations.AddField(
            model_name='designationmodulepermission',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Edit'),
        ),
        migrations.AddField(
            model_name='designationmodulepermission',
            name='can_print',
            field=models.BooleanField(default=False, verbose_name='Print'),
        ),
        migrations.AddField(
            model_name='designationmodulepermission',
            name='can_view',
            field=models.BooleanField(default=False, verbose_name='View'),
        ),
        migrations.RunPython(forwards_enable_actions_for_active_links, backwards_noop),
    ]
