# Generated by Django 5.0.7 on 2026-03-30 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0007_designationmodulepermission_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
        migrations.CreateModel(
            name='UserPermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_module_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users permission',
                'verbose_name_plural': 'Users permissions',
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add', models.BooleanField(default=False, verbose_name='Add')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Edit')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('can_view', models.BooleanField(default=False, verbose_name='View')),
                ('can_print', models.BooleanField(default=False, verbose_name='Print')),
                ('can_download', models.BooleanField(default=False, verbose_name='Download')),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_module_permissions', to='roles_permissions.module')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='roles_permissions.userpermissionprofile')),
            ],
            options={
                'verbose_name': 'Module link',
                'verbose_name_plural': 'Module links',
            },
        ),
        migrations.AddConstraint(
            model_name='usermodulepermission',
            constraint=models.UniqueConstraint(fields=('profile', 'module'), name='roles_permissions_user_profile_module_uniq'),
        ),
    ]
