# Generated by Django 5.0.7 on 2026-03-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0008_user_permission_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User role assignment', 'verbose_name_plural': 'User role assignments'},
        ),
    ]
