# Generated by Django 5.0.7 on 2026-03-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0009_userrole_verbose_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
