# Generated by Django 5.0.7 on 2026-04-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashhandover'),
        ('payments', '0002_paymentquickservice'),
    ]

    operations = [
    ]
