# Generated by Django 5.0.7 on 2026-04-20 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merge_0002_cashhandover_0002_paymentquickservice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentquickservice',
            new_name='payments_pa_hospita_6ff6cc_idx',
            old_name='payments_pa_hospita_8f1f74_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentquickservice',
            new_name='payments_pa_hospita_7c3692_idx',
            old_name='payments_pa_hospita_2dfc56_idx',
        ),
        migrations.AlterField(
            model_name='paymentquickservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='paymentquickservice',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
