# Generated by Django 5.0.7 on 2026-04-04 17:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipd', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('summary_notes', models.TextField(blank=True, default='')),
                ('treatment_given', models.TextField(blank=True, default='')),
                ('condition_at_discharge', models.TextField(blank=True, default='')),
                ('medications_on_discharge', models.TextField(blank=True, default='')),
                ('follow_up_advice', models.TextField(blank=True, default='')),
                ('total_billed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='ipd.ipdadmission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to='shared.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
