# Generated by Django 5.0.7 on 2026-03-19 18:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('next_visit_date', models.DateField(db_index=True)),
                ('advice', models.TextField(blank=True, default='')),
                ('followup_status', models.CharField(choices=[('pending', 'Pending'), ('called', 'Called'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reminder_status', models.CharField(choices=[('none', 'None'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='none', max_length=20)),
                ('reminder_channel', models.CharField(choices=[('in_app', 'In App'), ('sms', 'Sms'), ('whatsapp', 'Whatsapp'), ('email', 'Email'), ('other', 'Other')], default='in_app', max_length=30)),
                ('scheduled_reminder_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('call_remark', models.TextField(blank=True, default='')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('missed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('internal_remarks', models.TextField(blank=True, default='')),
                ('assigned_to_receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='called_followups', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='doctors.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='shared.hospital')),
                ('linked_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_status_changes', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='followups.followup')),
            ],
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['hospital', 'next_visit_date', 'followup_status'], name='followups_f_hospita_5f20f8_idx'),
        ),
        migrations.AddIndex(
            model_name='followupstatushistory',
            index=models.Index(fields=['followup', 'to_status'], name='followups_f_followu_2570b1_idx'),
        ),
    ]
