# Generated by Django 5.0.7 on 2026-03-19 17:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=250)),
                ('form', models.CharField(blank=True, default='', max_length=100)),
                ('strength', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=80)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='shared.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineReorderRule',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='shared.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='inventory.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('stock_in', 'Stock In'), ('dispense_out', 'Dispense Out'), ('return_in', 'Return In'), ('adjust', 'Adjust')], max_length=30)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.medicinebatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='shared.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='shared.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.unit'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['hospital', 'medicine', 'expiry_date'], name='inventory_m_hospita_e858ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together={('hospital', 'medicine', 'batch_no')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinereorderrule',
            unique_together={('hospital', 'medicine')},
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['hospital', 'medicine', 'batch'], name='inventory_s_hospita_a60b79_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['hospital', 'name'], name='inventory_u_hospita_041fc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['hospital', 'name'], name='inventory_m_hospita_c68958_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('hospital', 'sku')},
        ),
    ]
