# Generated by Django 5.0.7 on 2026-04-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_hsn_code_medicine_pack_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit_conversions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
