# Generated by Django 5.0.7 on 2026-04-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_medicinecategory_packaging_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinecategory',
            name='rule_type',
            field=models.CharField(choices=[('strip_based', 'Strip-based (allow loose)'), ('liquid', 'Liquid (no loose)'), ('flexible', 'Flexible (outer + retail + base)'), ('unit_only', 'Unit only')], db_index=True, default='unit_only', max_length=20),
        ),
    ]
