# Generated by Django 5.0.7 on 2026-04-06 07:32

import apps.opd_templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPDTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=apps.opd_templates.models.template_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OPD Template',
                'verbose_name_plural': 'OPD Templates',
                'ordering': ['key'],
            },
        ),
    ]
