# Generated by Django 5.0.7 on 2026-03-19 17:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uhid', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('merged', 'Merged')], db_index=True, default='active', max_length=20)),
                ('patient_type', models.CharField(blank=True, default='', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('emergency_tags', models.CharField(blank=True, default='', max_length=200)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='shared.hospital')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_patients', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line1', models.CharField(blank=True, default='', max_length=200)),
                ('line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientFamilyGroup',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_groups', to='shared.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.patientfamilygroup'),
        ),
        migrations.CreateModel(
            name='PatientGuardian',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientTag',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_tags', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='patients.patient')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patients.patienttag')),
            ],
        ),
        migrations.CreateModel(
            name='UHIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhid_sequences', to='shared.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'phone'], name='patients_em_patient_7a5259_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('disease', models.CharField(max_length=200)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'disease'], name='patients_ch_patient_f578a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allergy', models.CharField(max_length=200)),
                ('reaction', models.CharField(blank=True, default='', max_length=200)),
                ('severity', models.CharField(blank=True, default='', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'allergy'], name='patients_al_patient_f61cd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientActivity',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('status', 'Status'), ('remark', 'Remark'), ('thread', 'Thread')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('internal', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_activities', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'activity_type'], name='patients_pa_patient_87127b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patientfamilygroup',
            index=models.Index(fields=['hospital', 'name'], name='patients_pa_hospita_105aea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'uhid'], name='patients_pa_hospita_a786ba_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'phone'], name='patients_pa_hospita_d76189_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'first_name', 'last_name'], name='patients_pa_hospita_d813f5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'dob'], name='patients_pa_hospita_ecf9bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('hospital', 'uhid')},
        ),
        migrations.AddIndex(
            model_name='patienttag',
            index=models.Index(fields=['hospital', 'name'], name='patients_pa_hospita_d58252_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patienttag',
            unique_together={('hospital', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='patienttagassignment',
            unique_together={('patient', 'tag')},
        ),
        migrations.AddIndex(
            model_name='uhidsequence',
            index=models.Index(fields=['hospital', 'year'], name='patients_uh_hospita_44130e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uhidsequence',
            unique_together={('hospital', 'year')},
        ),
    ]
