# Generated by Django 5.0.7 on 2026-04-02 02:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='shared.hospital')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('hospital', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(blank=True, default='', max_length=50)),
                ('room_type', models.CharField(choices=[('ward', 'Ward'), ('personal', 'Personal Room'), ('shared', 'Shared Room'), ('icu', 'ICU'), ('emergency', 'Emergency')], default='ward', max_length=20)),
                ('is_ac', models.BooleanField(default=False)),
                ('daily_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_beds', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_rooms', to='shared.hospital')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='beds.floor')),
            ],
            options={
                'ordering': ['floor', 'room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_code', models.CharField(max_length=50)),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned')], db_index=True, default='available', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='shared.hospital')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='beds.bedroom')),
            ],
            options={
                'ordering': ['room', 'bed_number'],
                'unique_together': {('hospital', 'bed_code')},
            },
        ),
    ]
