# Generated by Django 5.0.7 on 2026-04-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_bedcleaningtask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bedcleaningtask',
            new_name='beds_bedcle_hospita_bfa120_idx',
            old_name='beds_bedcle_hospita_1cb331_idx',
        ),
        migrations.RenameIndex(
            model_name='bedcleaningtask',
            new_name='beds_bedcle_bed_id_fe0a6a_idx',
            old_name='beds_bedcle_bed_id_ee2414_idx',
        ),
    ]
