# Generated by Django 5.0.7 on 2026-03-31 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('staff', '0004_alter_department_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEarnedLeaveAllocation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('earned_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_applied', models.BooleanField(db_index=True, default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_leave_allocations', to='staff.designation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_leave_allocations', to='shared.hospital')),
            ],
            options={
                'ordering': ['-year', '-month', 'designation__name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDailyAttendance',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_index=True)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half day'), ('on_leave', 'On leave'), ('pending_regularization', 'Pending regularization')], db_index=True, default='incomplete', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='shared.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-attendance_date', 'staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeaveBalance',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('earned', 'Earned leave'), ('sick', 'Sick leave'), ('casual', 'Casual leave'), ('unpaid', 'Unpaid leave'), ('other', 'Other')], db_index=True, max_length=20)),
                ('balance_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_index=True)),
                ('requested_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_regularizations', to='shared.hospital')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularizations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularizations', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='attendance__hospita_bd8bc2_idx'), models.Index(fields=['staff', 'attendance_date'], name='attendance__staff_i_88d0f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('earned', 'Earned leave'), ('sick', 'Sick leave'), ('casual', 'Casual leave'), ('unpaid', 'Unpaid leave'), ('other', 'Other')], db_index=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('first_half', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('total_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to='shared.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='attendance__hospita_ed0f75_idx'), models.Index(fields=['staff', 'start_date', 'end_date'], name='attendance__staff_i_60fbf7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyearnedleaveallocation',
            constraint=models.UniqueConstraint(fields=('hospital', 'year', 'month', 'designation'), name='attendance_unique_monthly_earned_allocation'),
        ),
        migrations.AddIndex(
            model_name='staffdailyattendance',
            index=models.Index(fields=['hospital', 'attendance_date'], name='attendance__hospita_0563f4_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdailyattendance',
            index=models.Index(fields=['staff', 'attendance_date'], name='attendance__staff_i_3c74f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffdailyattendance',
            constraint=models.UniqueConstraint(fields=('hospital', 'staff', 'attendance_date'), name='attendance_unique_staff_date_hospital'),
        ),
        migrations.AddConstraint(
            model_name='staffleavebalance',
            constraint=models.UniqueConstraint(fields=('staff', 'leave_type'), name='attendance_unique_staff_leave_balance'),
        ),
    ]
