# Generated by Django 5.0.7 on 2026-04-01 06:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprover',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily suspend this approver without deleting the record.')),
                ('notes', models.TextField(blank=True, default='', help_text="Optional note (e.g. 'HR Manager', 'Backup approver').")),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvers', to='shared.hospital')),
                ('user', models.ForeignKey(help_text='User who is permitted to approve leave requests for this hospital.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_approver_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Approver',
                'verbose_name_plural': 'Leave Approvers',
                'ordering': ['hospital__name', 'user__email'],
                'unique_together': {('hospital', 'user')},
            },
        ),
    ]
