# Generated by Django 5.0.7 on 2026-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0002_receptionportalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='email',
            field=models.CharField(blank=True, default='health@vardaanhospitaljind.com', max_length=120),
        ),
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='hospital_name',
            field=models.CharField(blank=True, default='Vardaan Hospital', max_length=200),
        ),
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='phone',
            field=models.CharField(blank=True, default='+91-7082877717', max_length=40),
        ),
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='website',
            field=models.CharField(blank=True, default='www.vardaanhospitaljind.com', max_length=200),
        ),
    ]
