# Generated by Django 5.0.7 on 2026-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0003_alter_receptionportalsettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='address',
            field=models.CharField(blank=True, default='Jind, Haryana, 126102', max_length=255),
        ),
    ]
