# Generated by Django 5.0.7 on 2026-04-13 01:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOutletSettings',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('mobile', models.CharField(blank=True, default='', max_length=40)),
                ('gst_number', models.CharField(blank=True, default='', max_length=40)),
                ('dl_number', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_outlet_settings', to='shared.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
