# Generated by Django 5.0.7 on 2026-04-13 08:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacypurchasechallan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pharmacysupplier',
            new_name='pharmacy_ph_hospita_8a5e91_idx',
            old_name='pharmacy_sup_hosp_name_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacysupplier',
            new_name='pharmacy_ph_hospita_85c9e0_idx',
            old_name='pharmacy_sup_hosp_act_idx',
        ),
        migrations.AlterField(
            model_name='pharmacypurchasechallan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacypurchasechallan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacypurchasechallan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pharmacypurchasechallanline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacypurchasechallanline',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacypurchasechallanline',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
