# Generated by Django 5.0.7 on 2026-03-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('shared', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='staff.department'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profiles', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='staff_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profiles', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctordailyavailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_availabilities', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorweeklyschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorweeklyschedule',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedules', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='staff.department'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.specialty'),
        ),
        migrations.AddIndex(
            model_name='doctordailyavailability',
            index=models.Index(fields=['hospital', 'doctor', 'date'], name='doctors_doc_hospita_58e9ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctordailyavailability',
            unique_together={('hospital', 'doctor', 'date')},
        ),
        migrations.AddIndex(
            model_name='doctorweeklyschedule',
            index=models.Index(fields=['hospital', 'doctor', 'day_of_week'], name='doctors_doc_hospita_d7c4a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorweeklyschedule',
            unique_together={('hospital', 'doctor', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['hospital', 'name'], name='doctors_spe_hospita_711aae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['hospital', 'is_active'], name='doctors_doc_hospita_a9a52e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['department', 'name'], name='doctors_doc_departm_69367e_idx'),
        ),
    ]
