# Generated by Django 5.0.7 on 2026-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
