# Generated by Django 5.0.7 on 2026-03-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='staff_profile',
        ),
    ]
