# Generated by Django 5.0.7 on 2026-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctorprofile_staff_profile'),
        ('staff', '0004_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctorprofile',
            name='doctors_doc_departm_69367e_idx',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='departments',
            field=models.ManyToManyField(related_name='doctors', to='staff.department'),
        ),
    ]
