# Generated by Django 5.0.7 on 2026-03-19 17:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField()),
                ('appointment_datetime', models.DateTimeField(db_index=True)),
                ('consultation_type', models.CharField(choices=[('new', 'New'), ('followup', 'Followup'), ('walk_in', 'Walk In')], default='new', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('queue_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('reason_for_visit', models.TextField(blank=True, default='')),
                ('internal_remarks', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
    ]
