# Generated by Django 5.0.7 on 2026-04-17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
        ("notifications", "0001_treatment_staff_assignment_and_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh_key", models.CharField(max_length=255)),
                ("auth_key", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webpush_subscriptions", to="shared.hospital")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webpush_subscriptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="notificatio_user_id_466021_idx"),
                    models.Index(fields=["hospital", "is_active"], name="notificatio_hospita_8c0ece_idx"),
                ],
            },
        ),
    ]
