# Generated by Django 5.0.7 on 2026-04-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_webpushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='notificatio_user_id_0018e4_idx',
            old_name='notificatio_user_id_466021_idx',
        ),
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='notificatio_hospita_826c51_idx',
            old_name='notificatio_hospita_8c0ece_idx',
        ),
    ]
